		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="<?= htmlspecialchars( $px->href('/common/styles/bootstrap/css/bootstrap.min.css') ); ?>">
		<!-- Optional theme -->
		<link rel="stylesheet" href="<?= htmlspecialchars( $px->href('/common/styles/bootstrap/css/bootstrap-theme.min.css') ); ?>">
		<!-- Latest compiled and minified JavaScript -->
		<script src="<?= htmlspecialchars( $px->href('/common/styles/bootstrap/js/bootstrap.min.js') ); ?>"></script>
		<!-- style.css -->
		<link rel="stylesheet" href="<?= htmlspecialchars( $px->href('/common/styles/style.css') ); ?>">
