language: php
php:
  - "5.5"
  - "5.4"

before_install:
  - composer selfupdate

before_script:
  - composer install

script:
  - ./vendor/phpunit/phpunit/phpunit "./px-files/_sys/tests/"

notifications:
  emails:
    - tomk79@gmail.com
  on_success: always
  on_failure: always
