os:
  - linux

language: php

dist: trusty

php:
  - "7.4"
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"

before_install:
  - composer selfupdate

before_script:
  - composer install

script:
  - ./vendor/phpunit/phpunit/phpunit

notifications:
  emails:
    - tomk79@gmail.com
  on_success: always
  on_failure: always
