# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

# Try out "interactive-mode"
os: Windows Server 2012 R2

# build version format
version: "{build}-{branch}"

# Set a known clone folder
clone_folder: C:\projects\PxFW-2.x

# branches
branches:
  only:
    - master
    - develop

# fix lineendings in Windows
init:
  - git config --global core.autocrlf input
  - git config --global user.name "Tomoya Koyanagi"
  - git config --global user.email tomk79@gmail.com

# # what combinations to test
# environment:
#   matrix:
#     # Node.js
#     - nodejs_version: "0.10"
#     - nodejs_version: "0.12"
#     # io.js
#     - nodejs_version: "2"

# matrix:
#   fast_finish: true
#   allow_failures:
#     - nodejs_version: "0.10"
#     - nodejs_version: "2"

# services:
#   - iis  

# Get the latest stable version of Node 0.STABLE.latest
# Install scripts. (runs after repo cloning)
install:
  # # Set MySQL.
  # - cp tests/my.cnf c:\
  # - cinst mysql
  # - SET PATH=C:\tools\mysql\current\bin\;%PATH%

  # Set bash.
  - cinst mingw-get
  - set PATH=%PATH%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin
  - mingw-get install mingw-developer-toolkit

  ## Set PHP.
  - cinst php
  - SET PATH=C:\tools\php\;%PATH%
  - cd C:\tools\php
  - copy php.ini-production php.ini
  - echo date.timezone="Asia/Tokyo" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_gd2.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_mysql.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_xsl.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo output_buffering = Off >> php.ini
  - echo default_charset = UTF-8 >> php.ini
  - echo mbstring.language = Japanese >> php.ini
  - echo mbstring.encoding_translation = On >> php.ini
  - echo mbstring.http_input = UTF-8 >> php.ini
  - echo mbstring.http_output = pass >> php.ini
  - echo mbstring.internal_encoding = UTF-8 >> php.ini

  - php -v
  # - php -r "phpinfo();"

  ## Set Composer.
  - cd C:\projects\PxFW-2.x
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - php composer.phar --version
  - php composer.phar install


build_script:
  - cmd: php vendor\phpunit\phpunit\phpunit.php



test: off
deploy: off


notifications:
  # Email
  - provider: Email
    to:
      - tomk79@gmail.com
    # subject: 'Build {{status}}'                  # optional
    # message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_status_changed: true
